### PR TITLE
Fix OS X build.

### PR DESCRIPTION
**Pull request by paulp**
Proving again untested code is always broken. I hope we have
an automated cross-platform testing solution in place before
we get much more attention.

### CODE REVIEW

**Comment by EECOLOR** [comment]
Wow, I did not realize it would not compile the `_darwin` files...

I have added a commit which at least locally tells me that there is a compilation problem. I have almost 0 experience in bash. So you can probably make this a bit more fancy. At least `cc.sh` now alerts me to these types of problems.

**Comment by paulp** [comment]
That way of finding files won't work in general. GOROOT isn't necessarily set (mine isn't.) 

It doesn't compile the _darwin files because typically it can't. Look at the darwin file [when I first checked it in](https://github.com/suffuse/go-suffuse/blob/ba7fbf318f632f970f1d6a6f5f4d995341b717ab/platform_darwin.go), and try compiling that on linux. There's no Birthtimespec to be found on linux.

There's no way to ensure it compiles on all platforms which doesn't amount to simulating all platforms, whether locally or remotely, via docker, virtualbox, or similar.

**Comment by paulp** [comment]
I guess the birthtimespec is still in there. So do you mean it alerts you to these kinds of problems but you have to know which errors are expected and which ones you introduced? That might work while the platform-specific parts are so tiny but I think the gain is minimal.

**Comment by EECOLOR** [comment]
It did give the compile error about the `MNT_FORCE` which means it does compile that file now. I stole the code from https://github.com/davecheney/golang-crosscompile

**Comment by paulp** [comment]
You mean it obtains the OS X includes from somewhere? That's great if so (on a phone can't really check)

**Comment by EECOLOR** [comment]
I don't have a clue. I just tried to reproduce the error you fixed in that commit.

**Comment by paulp** [comment]
Right. What I mean is that MNT_FORCE exists on both OSX and linux, but `time_t st_birthtime` in `struct stat` only exists on OSX. Go references to the latter will only compile on OSX unless something is arranging access to the platform-specific Go files generated from the platform-specific C headers.

**Comment by paulp** [comment]
Indeed cross-building does work. I tried to make it a bit more automatic.

**Comment by EECOLOR** [comment]
Great job! Do you thing we need to use that one in travis too?

**Comment by EECOLOR** [comment]
As a coincidence the CircleCI guys enabled our OSX environment. It was [quite a pain](https://github.com/suffuse/go-suffuse/commits/circleci) to get it working. I included the result here.

**Comment by paulp** [comment]
Nice. Shades of the 70 slot machine pulls it took me to get the bazil.org tests working.

If by some miracle the gox cross-build works on travis without another few dozen pulls, we should use it. One way or another we need machine verification that it builds on all platforms and that the tests pass on at least one. (Tests passing on all platforms we need but can wait.) What is the least painful route to that outcome I don't know. All these various forms of virtualization to battle through wear down the soul.

**Comment by EECOLOR** [comment]
Do you think this can be merged?

**Comment by paulp** [comment]
Sure. That's six days elapsed to get the one-line fix to the build in. Of course it'd be better if such situations never arose, which is what we're striving for in this very PR.

**Pull request merged**
