### PR TITLE
fix a couple of commands and command output

### PR DESCRIPTION
**Pull request by rintcius**

### CODE REVIEW

**Comment by paulp** [comment]
That's not going to work. Home directory locations aren't stable, not even within operating systems.

It's a good point that /mnt isn't user-writable out of the box, probably not on either osx or linux.

Not sure what the ideal remedy is.

**Comment by paulp** [comment]
Oh, I see now, the README mixes and matches mount points which wasn't visible in the diff. Now I don't know why the tests failed. How did this happen? Notice 00:00 vs. 2015. (Presumably has nothing to do with a README change.)

```
-rw-r--r-- 1 13 Jul 10 00:00 seq.txt#5,10p            | -rw-r--r-- 1 13 Jul 10  2015 seq.txt#5,10p
-rw-r--r-- 1 6 Jul 10 00:00 seq.txt#1,3p              | -rw-r--r-- 1 6 Jul 10  2015 seq.txt#1,3p
```

**Comment by paulp** [comment]
See #30 for an explanation of the failure. The build was already failing despite the "passing" badge.

**Comment by rintcius** [comment]
Indeed, I used `~/mnt` in the first place because that's what I started using, after having pasted the first examples in my terminal. After seeing the mismatch, I thought it made more sense to use `~/mnt` than `/mnt` since it's just a little sandbox example.

Regarding the different format, I don't know the answer to your question, but this is my output:

```
user@MacBook-Pro:~/workspaces/go/src$ ls -l ~/mnt/seq.txt#5,10p
-rw-r--r--  1 user  staff  13 Jul 11 13:38 /Users/user/mnt/seq.txt#5,10p
user@MacBook-Pro:~/workspaces/go/src$ ls -l ~/mnt/seq.txt#1,3p
-rw-r--r--  1 user  staff  6 Jul 11 13:38 /Users/user/mnt/seq.txt#1,3p
```

**Comment by rintcius** [comment]
Regarding "That's not going to work. Home directory locations aren't stable, not even within operating systems". Not sure what you mean exactly, the newly documented commands worked for me and I think they should in general succeed on linux & OS X (unless eg ~/mnt is already there). Or do you mean that the output, in particular `/home/user` will be different?

Just let me know if you like any changes.

**Comment by paulp** [comment]
I mean the tests unfortunately depend on strings matching exactly, so anything which exposes the local value of ~ will fail.

**Comment by paulp** [comment]
(When I wrote that I thought this change was to the test, and that was why it was failing. Obviously the README can tolerate the presence of ~, it's the tests which can't.)

**Comment by paulp** [comment]
All of this confusion is due to my now-shattered belief that tests failing on a pull request can safely be attributed to the content of the pull request, since of course the tests are passing on master. That's why I find what happened with travis so unacceptable.

**Comment by rintcius** [comment]
Right, I agree. Thanks for the explanation.

**Comment by EECOLOR** [comment]
@rintcius Sorry for the confusion. You changes have been merged

**Comment by rintcius** [comment]
NP @EECOLOR - thanks for merging

**Pull request merged**
