### PR TITLE
First steps for a config example

### PR DESCRIPTION
**Pull request by EECOLOR**
tests are failing, checking the behavior of travis

### CODE REVIEW

**Comment by EECOLOR** [comment]
I did a `push -f` on this one and verified it started a build for `e12a9bf`

**Comment by EECOLOR** [comment]
The thing with Travis is that it does not rebuild the pull request, only the push. It does not matter if the push is with force or not.

**Comment by EECOLOR** [comment]
About this pr, could you check it on OS X? The `-go` arguments changed the output which I did not notice.

**Comment by EECOLOR** [comment]
I had another problem with the dates on this one. So I force-pushed again. This time travis seems to rebuild the pull request.

**Comment by EECOLOR** [comment]
Ahh, now I understand, it creates (or uses) a fake or temporary commit that is the result of the pull request. That's why the commit uuid's are unknown. [Merge 690530f into 30e2709](https://github.com/suffuse/go-suffuse/commit/2eb82d20ea74b463fa8db64794806eca4936a122)

**Comment by paulp** [comment]
```
=== RUN TestSed
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
```

We really have to find a more efficient way to do this. Maybe we should use `tree` which seems more likely to behave the same across platforms.

**Comment by paulp** [comment]
Standard OSX ls has no -- style options at all.

**Comment by EECOLOR** [comment]
Damnit....

I'll try `tree`...

**Comment by EECOLOR** [comment]
`tree` wouldn't work in this case because it's an on-demand file

**Comment by paulp** [comment]
Ah, yes. Maybe we should use `stat`.

**Comment by paulp** [comment]
Actually, definitely we should use stat, if necessary with an explicit format string.

**Comment by EECOLOR** [comment]
What format string do you propose?

**Comment by paulp** [comment]
The one with whatever we're trying to test. Not sure. `"%p %z %N"` are the only ones I'm mostly sure would be stable.

**Comment by EECOLOR** [comment]
What does `stat -c "%a %Z %s %n" seq.txt#5,10p # Arbitrary sed commands, different sized files.` give you?

For me it prints: `644 -6795364577 13 seq.txt#5,10p`

**Comment by paulp** [comment]
You have a sixth sense for finding the incompatibilities. OSX stat doesn't even have a -c.

**Comment by EECOLOR** [comment]
The how do you supply the format? (btw, linux does not have a `%d`)

**Comment by paulp** [comment]
WTF, that's the linux format string option? They couldn't give us this one thing. On OSX it's -f for the format string.

**Comment by paulp** [comment]
Next idea: standardize on gnu stat.

**Comment by EECOLOR** [comment]
Oh crap, that's the file system... And `--format` does not exist on OSX

**Comment by paulp** [comment]
Looks like we have identical stats if I use the stat from gnu coreutils. Brew installs it as "gstat" and all the other linux-identical versions as "gwhatever".

**Comment by paulp** [comment]
We could choose the program to run with "if there's a gstat, use that, otherwise stat."

**Comment by paulp** [comment]
It's another point of testing failure of course, but it can be recognized and `brew install coreutils` will make it go away.

**Comment by EECOLOR** [comment]
Probably not a problem, but there is this:

> gstat - manual page for Ganglia Status Tool

Makes me think we should just use a go util to check file info.

**Comment by paulp** [comment]
Heh, we can call OsLstat() and just print it with %+v.

**Comment by EECOLOR** [comment]
I'll go after it tomorrow, I ran out of time

**Comment by paulp** [comment]
For reference,

```
  fi, _ := s.Out.Join("bigfile.txt").SysStatLink()
  Printf("\n%+v\n", fi)
```

Results in

```
{Dev:788530360 Mode:33188 Nlink:1 Ino:219163550 Uid:501 Gid:0 
Rdev:0 Pad_cgo_0:[0 0 0 0] Atimespec:{Sec:1436911239 Nsec:0} 
Mtimespec:{Sec:1436911239 Nsec:0} Ctimespec:{Sec:1436911239 Nsec:0} 
Birthtimespec:{Sec:1436911239 Nsec:0} Size:48894 Blocks:96 
Blksize:1048576 Flags:0 Gen:0 Lspare:0 Qspare:[0 0]}
```

I don't know if there's any way to filter the fields. But we can just print the handful of interest directly.

**Comment by EECOLOR** [comment]
Watch out for the force push.

How does this work on your device?

**Comment by paulp** [comment]
```
=== RUN TestSed
--- PASS: TestSed (0.41s)
=== RUN TestJsonToYaml
--- PASS: TestJsonToYaml (0.26s)
```

**Comment by EECOLOR** [comment]
Awesome :-)

**Comment by EECOLOR** [comment]
Whoohoo! :beers:

**Pull request merged**
